# Goal - approach the start of a swath defined by map_points (poses in map frame)
geometry_msgs/PoseStamped[] map_points
string planner_id
string controller_id
string path_pub_topic
string behavior_tree
---
# Result
uint16 error_code
uint16 NONE=0
uint16 CANCELLED=1
uint16 FAILED=2
---
# Feedback
float32 distance_remaining
